### ISSUE TITLE
NSS +sqllite vulnerabilities

### ISSUE THREAD

**Issue by edfenergy-stevebowerman** [gotenberg/gotenberg#1006]
Hi,

We are running gotenberg on AWS ECR and inspector (runtime vulnerability scanner) is detecting the following CVE's with the NSS  package

https://security-tracker.debian.org/tracker/CVE-2024-0743
https://security-tracker.debian.org/tracker/CVE-2024-6609

At the sqllite package:
https://security-tracker.debian.org/tracker/CVE-2023-7104

Is the a workaround or planned fix for these?

thanks

**Comment by gulien** [comment]
Hey @edfenergy-stevebowerman,

Next time, please follow the steps mentioned in https://github.com/gotenberg/gotenberg?tab=security-ov-file#readme.

Gotenberg uses `debian:12` (aka *bookworm*) as base OS, which is supposed to be [supported by security and release teams](https://wiki.debian.org/LTS) and is the future LTS. But the mentioned issues do not have a fix available on *bookworm* yet, so I cannot do much here.

Remember that Gotenberg is not a professional occupation of mine, and I'm working on it on my free time. If this issue is really impacting your business, please share your solution here or consider [sponsoring](https://github.com/sponsors/gulien) my work so that I may prioritize your issue 😉
