### ISSUE TITLE
TOC generation

### ISSUE THREAD

**Issue by tonyellow** [gotenberg/gotenberg#233]
I reopened my previous feature request as I didn't have a chane to reply in it. 

I am not generating pdf from word but from html. Do you have an advice on how to generated a table of contents (with pagenumbers) for a pdf generated from html?

> Thanks for the kind words! 
> 
> IMO it should be done by the user, not Gotenberg. For instance you may generate a TOC with Word directly 😄
> 
> _Originally posted by @gulien in https://github.com/thecodingmachine/gotenberg/issues/186#issuecomment-610349104_

**Comment by sebastian-schlecht** [comment]
@tonyellow this might help

https://link.medium.com/zAX2yRbu69

**Comment by serge-melis** [comment]
Though, in an automated workflow there's no step to 'Generate a TOC with Word directly'.

**Comment by serge-melis** [comment]
Would you be open to a pull request to enable this using the unoconv parameter?

**Comment by gulien** [comment]
@serge-melis do you have more details about what to do exactly? 🤔

**Comment by serge-melis** [comment]
Hi @gulien great to hear from you! We are generating a word document using phpWord, this includes a Table of Contents object. When we open the result in OpenOffice, it will ask us if we want to (re)generate the Table of Contents, as this is not actually done during the generation of the document because of the variable length.

So far, running the document through unoconv does not allow us to have the Table of Contents (re)generated. I was hoping there was some sort of flag we could passthrough Gotenberg to have unoconv enable this.

**Comment by gulien** [comment]
That would be great 😄 AFAIK, I have not heard of such option in `unoconv`..

**Comment by serge-melis** [comment]
We have looked into it, and kind of came up blank. There are some workarounds with a macro, but could not get it to work

Serge

________________________________

**Comment by jonnisell** [comment]
> @tonyellow this might help
> 
> https://link.medium.com/zAX2yRbu69

The mentioned solution may work with the tools suggested in the article, but I haven't gotten it to work using the pdf-merge funtionality in the PDFengine section of Gotenberg. If I generate a TOC pdf and merge it with the already exisiting pdf, the links aren't clickable, but only marked as HTML links. This happens regardless merging PDFs, AKAICS

p.s. Gotenberg is a very good tool in many other cases
