### ISSUE TITLE
Prometheus metrics per module

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#323]
Related #318.

@ArcRiiad

**Comment by gulien** [comment]
See #318

**Comment by gulien** [comment]
@ArcRiiad As Gotenberg v7 is now starting a dedicated Chromium instance per request, I guess CPU/Memory usage details are enough for you? Meaning, there might not be a need for custom Prometheus metrics.

**Comment by ekeuus** [comment]
> @ArcRiiad As Gotenberg v7 is now starting a dedicated Chromium instance per request, I guess CPU/Memory usage details are enough for you? Meaning, there might not be a need for custom Prometheus metrics.

Not 100% relevant to this topic, but how does this affect resource usage and the request duration if more steps need to be made for the conversion to be done?

**Comment by gulien** [comment]
Hello @ekeuus 

Previous, there was a long-running Chromium process that grabbed more and more RAM over time, and the Go code around this was hard to maintain.

Now, Gotenberg creates a Chromium process for each request related to the `chromium` module. This method probably mitigates the memory leak problem, but it makes the code easier to maintain. If extra steps are required, no problem; Gotenberg kills the Chromium process once it finishes the conversion.

Regarding resource usage, I'd like feedback from the community 😄 , but I have set up demo URLs to have a kind of overview (see https://gotenberg.dev/docs/get-started/live-demo).

On the other hand, this particular change should not impact a request duration drastically. Gotenberg may take more time to convert some pages, but that's because he's now checking underlying requests (AJAX, etc.) to verify if they match the allow/deny lists.

**Comment by ArcRiiad** [comment]
Hi @gulien, I forget to give my answer earlier 😅 

First, thanks for this new release, you guys rock!

Concerning the custom metrics, I still think it's a good idea to provide a way to track the number of the ongoing pdf or other module renderings. IMO in this context, it's more convenient to scale these kinds of services based on the current state rather than the resource usage(it's like trying to scale up a pull of workers by checking the current queue size rather than the memory used by the queue, and even better when you have both 😄) so having this metric will be useful.

I will try to draft in my spare time a module in the same way you did with the healthcheck endpoint 😃

**Comment by gulien** [comment]
Thanks for the feedback @ArcRiiad 😄 I'll try to find a generic solution with the module system 👍

**Comment by gulien** [comment]
@ArcRiiad just a quick follow up (sorry for the delay); I plan to release a new version in the next two weeks with prometheus support 👍
