### ISSUE TITLE
PDF/A-1a conversion is not passing validation

### ISSUE THREAD

**Issue by Vrex123** [gotenberg/gotenberg#395]
It appears like unoconv is not adding necessary metada to resulting PDF, so it not conforms to PDF/A-1a standart.

I validated PDF here https://avepdf.com/pdfa-validation and on few other online tools, results are same.

I haven't saved validationn report, but it's easy to reproduce wtih any converted PDF. As long as I remember,  XMP metada, StructTreeRoot dictionary and something else missing 

PDF that I was checking was converted from HTML using chromium module

**Comment by gulien** [comment]
Converting a `.docx` file plus using the form field `pdfFormat` with `PDF/A-1a` resulted to the following PDF:

[da670ffe-8c6f-457e-ac2c-137e5bca0807.pdf](https://github.com/gotenberg/gotenberg/files/7712313/da670ffe-8c6f-457e-ac2c-137e5bca0807.pdf)

It validates against PDF/A-1a standard 🤔 

Same for the following PDF that originates from HTML conversion:

[049e9f6b-a3b2-4ce2-b1d9-bd3e1e5611a6.pdf](https://github.com/gotenberg/gotenberg/files/7712340/049e9f6b-a3b2-4ce2-b1d9-bd3e1e5611a6.pdf)

**Comment by gulien** [comment]
😄 no problem, it happens to the best of us!
I guess the issues are related on how LibreOffice parses and transforms the PDF from Chrome in order to achieve the PDF/A-1a conversion.

The mecanism is far from perfect, but until I or the community find a better tool for that task, we’re kinda stuck. 

Developing a custom PDF engine from scratch is also too far time consuming for me, and the best options for quality are paid softwares / SaaS because they can afford to put their effort on such endeavor.
