### ISSUE TITLE
Feature: split pdf into multiple pdfs

### ISSUE THREAD

**Issue by ps73** [gotenberg/gotenberg#441]
It would be nice to have an option to split multipage pdfs into multiple pdfs like convert but the other way around.

**Comment by nodecentral** [comment]
Hi, keen to know how this enhancement is progressing, as I can see the option is available via `pdftk` - guide here too - https://charlieharvey.org.uk/page/howto_breaking_pdfs_up_into_mutiple_pages

**Comment by markitosgv** [comment]
It would be an amazing feature, the pdftk binary gives you the option to do splitting, I don't think it would be very difficult to implement.

**Comment by gulien** [comment]
Hello,

it should be doable after 8.x release. It’s not as straightforward as it seems, as I’ll have to implement it in others PDF engine too. Also, it requires some logic update (if one want to convert + split in a single request for instance).

**Comment by wjkoh** [comment]
Thank you for creating Gotenberg! Would it be possible to add the ability to truncate a PDF file to a specified number of pages, such as 300? This functionality would be incredibly useful for all AI applications, as many large language model APIs nowadays impose limits on the number of pages that can be uploaded.

**Comment by wjkoh** [comment]
Hi everyone, Gotenberg already [integrates QPDF effectively](https://github.com/gotenberg/gotenberg/blob/v8.7.0/pkg/modules/qpdf/qpdf.go). What I'm aiming to achieve is relatively simple using QPDF: `qpdf big.pdf --pages . 1-300 -- first-300-pages.pdf`

This use case is a subset of the split functionality but might cover most users' needs. By exposing a split function for a single input file only, we can keep it straightforward with just two inputs: a file and a single page range. Multiple ranges aren't necessary since users can call the endpoint as many times as needed.

**Comment by gulien** [comment]
I’ve identified the following use cases for the « split » feature:

1. Extract specific pages (e.g. page ranges).
2. Split into single page.
3. Split at intervals.
4. Split at bookmarks.

**Comment by gulien** [comment]
@wjkoh `gotenberg/gotenberg:edge` should be available within ~1 hour with this feature.

The new route `/forms/pdfengines/split` accepts one or PDF files plus:

* `splitMode` - either *intervals* or *pages*
* `splitSpan` - either the interval range or the page range.

Note that the `/forms/chromiums/convert/*` and `/forms/libreoffice/convert` routes also accept those form fields.
