### ISSUE TITLE
Transparent PNGs in docx to PDF conversion

### ISSUE THREAD

**Issue by esglobal** [gotenberg/gotenberg#472]
I tried everything I could but I can't find a way to convert a docx file that has a transparent PNG and keep the transparency. 

So the docx has a yellow background and I have a transparent PNG top right. The docx file looks good but the converted PDF has white background around the PNG.

Has anyone had this issue? Couldn't find anything in the docs.

**Comment by esglobal** [comment]
The thing is when I do on a separate machine, a standard manual conversion with libreoffice works like a charm.

**Comment by gulien** [comment]
Interesting, what's the Libreoffice version?

**Comment by esglobal** [comment]
LibreOffice 6.4.7.2 and unoconv 0.7 on both machines

**Comment by esglobal** [comment]
Nah sorry the docker host has LibreOffice 6.4 my bad

**Comment by gulien** [comment]
Gotenberg relies on LibreOffice 7.x, so it could be the culprit 🤔

**Comment by esglobal** [comment]
I'll try update LibreOffice to 7.x and run the same conversion. I don't believe the could've dropped support for transparency, but maybe there are some new parameters.

**Comment by gulien** [comment]
Yep or a bug, it happens 🤷‍♂️

**Comment by esglobal** [comment]
Hi @gulien so I used the standard `libreoffice --headless --convert-to pdf:writer_pdf_Export test.docx` to convert on both versions and LibreOffice 6 preserves PNG transparency, while LibreOffice 7 doesn't. 

I'll keep digging and if I will find something useful I'll post it here. Thanks for looking into it

**Comment by esglobal** [comment]
I can confirm 100% that Gotenberg v6 works like a charm, while v7 has issues with PNG transparency in docx documents. 

I'll stick to v6 until v7 bug will be fixed. If it'll be fixed

**Comment by gulien** [comment]
Hello @esglobal 👋 

Sorry for the delay. There is a new form field called `losslessImageCompression` that is set to *false* by default. I wonder if previous versions of LibreOffice where converting images to PNG by default instead of JPEG.

Setting it to *true* might bring back transparency. If that’s not the case, there isn’t much I can do on my level, and I’d suggest to post an issue on the LibreOffice bug tracker.

Feel free to reopen this issue of needed 👍
