### ISSUE TITLE
Converting PDF to PDF/A-1a results in PDF/A-1b document instead on `:edge`

### ISSUE THREAD

**Issue by stumpylog** [gotenberg/gotenberg#746]
Given [sample1.pdf](https://github.com/gotenberg/gotenberg/blob/main/test/testdata/pdfengines/sample1.pdf), the cURL command below has started returning a PDF/A-1b document instead of the requested PDA/A-1a document, as checked/reported via pikepdf and a few of the random validators.

```
curl --request POST --url http://localhost:3000/forms/pdfengines/convert --header 'Content-Type: multipart/form-data' --form files=@'sample1.pdf' --form 'pdfa=PDF/A-1a' -o result.pdf
```

I'm testing with the latest edge, `docker.io/gotenberg/gotenberg:edge@sha256:5f6acd4bff3c6bb3d3ee618fdcc9ddb481253c1d3302bf32cb2a7985ff1e8d50`, so I assume up to date with 4e5c1aba2e05e61ea0501fc5df768fda6f625a58. Without earlier digests, I can't pinpoint where this began, but it is not present in 7.10.1

**Comment by stumpylog** [comment]
The resulting file: 
[result.pdf](https://github.com/gotenberg/gotenberg/files/13641500/result.pdf)

**Comment by gulien** [comment]
Thanks for testing the edge release!
Gotenberg still call LibreOffice in the same manner as before, so I guess something happened upstream. A new LibreOffice version that introduced a bug?

**Comment by gulien** [comment]
LibreOffice versions:

* 7.10.1 = `LibreOffice 7.5.8.2 50(Build:2)`
* edge = `LibreOffice 7.6.4.1 60(Build:1)`

**Comment by gulien** [comment]
The [ 7.6 release notes](https://wiki.documentfoundation.org/ReleaseNotes/7.6#Filters):

> Export to PDF v.1.7 by default. [core commit e624e](https://git.libreoffice.org/core/commit/e624e07cc54c408bb86bd2e52cfed3c7ec59fb4a) (Michael Stahl, allotropia)
[Tagged PDF](https://help.libreoffice.org/7.6/en-US/text/shared/01/ref_pdf_export_general.html) is now produced by default, for improved accessibility. (To further improve your PDF's accessibility, the [PDF/UA](https://help.libreoffice.org/7.6/en-US/text/shared/01/ref_pdf_export_universal_accessibility.html) option is available in the export dialog and will trigger the [Accessibility Check](https://help.libreoffice.org/7.6/en-US/text/swriter/01/accessibility_check.html) tool). [tdf#39667](https://bugs.documentfoundation.org/show_bug.cgi?id=39667) (Samuel Mehrbrodt, allotropia)
Exporting as a hybrid PDF now stores the original ODF document as a PDF compatible file attachment. [core commit e052f](https://git.libreoffice.org/core/commit/e052f6e1d49a5289411b31561d6e310bf414d896) (Tomaž Vajngerl, Collabora)
Fix glyph size mismatch and overlap when printing of variable fonts. [tdf#156151](https://bugs.documentfoundation.org/show_bug.cgi?id=156151) (Khaled Hosny, TDF)
Fix missing or incorrect overline color when exporting to PDF. [tdf#48707](https://bugs.documentfoundation.org/show_bug.cgi?id=48707) (Khaled Hosny, TDF)
Fix position of CJK emphasis marks when exporting to PDF. [tdf#115321](https://bugs.documentfoundation.org/show_bug.cgi?id=115321) (Khaled Hosny, TDF)
Fix blank text for the default instance of CFF2 variable fonts when exporting to PDF. [tdf#155161](https://bugs.documentfoundation.org/show_bug.cgi?id=155161) (Khaled Hosny, TDF)
Fix underline position of Liberation fonts when exporting to PDF. [tdf#154235](https://bugs.documentfoundation.org/show_bug.cgi?id=154235) (Khaled Hosny, TDF)

I don't see any changes here nor in the linked commits that's could explain our issue.

@stumpylog could you try to set `pdfua` to `true` with Gotenberg `7.10.1` to check if it returns `PDF/A-1b` instead of `PDF/A-1a`?

**Comment by stumpylog** [comment]
On 7.10.1, using `--form 'pdfa=PDF/A-1a' --form 'pdfua=true'` results in a A1 file.  leaving off `pdfua` also results in an A1 file.  Setting `pdfua=false` is also an A1 file.  So 7.10.1 is always returning an A1 file from this route when requested.

**Comment by gulien** [comment]
Looks like an upstream bug, thanks 👍

**Comment by gulien** [comment]
So it's actually not a bug: https://git.libreoffice.org/core/+/c4b12d06698402984b3ffdbd2c139f261fa35ca1%5E%21.
Long story short, LibreOffice stated that it was producing PDF/A-1a PDF, which was true for simple documents, but most of the time it was actually producing PDF/A-1b. Because of some metadata, some validators were still seeing those as PDF/A-1a compliant, where in fact it was not the case.

See also https://bugs.documentfoundation.org/show_bug.cgi?id=153472.

I guess I have to update the "valid" PDF/A versions handled by Gotennberg.
