### ISSUE TITLE
Convert should fail when Chromium throws a err::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Neirda24** [gotenberg/gotenberg#913]
As the title suggest, I think Gotenberg should return a 404 or similar when Chromium throws a err::ERR_CONNECTION_REFUSED here is an example :

```
gotenberg-1  | {"level":"debug","ts":1719471864.3495355,"logger":"chromium.browser","msg":"<- {\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"7458B3B7335C136ABA12568DEFD5A756\",\"timestamp\":141894.928028,\"type\":\"Document\",\"errorText\":\"net::ERR_CONNECTION_REFUSED\",\"canceled\":false},\"sessionId\":\"EB1CF54DB4678427B493F65D718BCE0D\"}"}
```

To reproduce : I simply set URL not accessible by Gotenberg.

**Comment by gulien** [comment]
Hello @Neirda24,

I wonder if it happens too if a resource (CSS whatever) is not reachable.

**Comment by Neirda24** [comment]
No idea to be honest but probably yes. I think if it concern the page itself it should return a 404. If it concern one of the asset.... Either a failure (like 400) or a way to configure : ignore (per asset or per page). WDYT ?

**Comment by Neirda24** [comment]
Ok I just tried with a reference to a CSS file which is not found (using the URL route) and no errors in debug logs. If we could at least get this kind of errors through headers it would allow to have specific error handling on client side.

**Comment by gulien** [comment]
Thanks for the details! 👍

**Comment by gulien** [comment]
Fixed in https://github.com/gotenberg/gotenberg/commit/f87362ec1b05b9af134ea94a3ecb321fed423c3d.

It will now return a *400 Bad Request* on `net::ERR_CONNECTION_REFUSED`. I'm not a fan of *404 Not Found*, as it means that the resource was not found while actually it's just the server that refused the connection 😄 

`gotenberg/gotenberg:edge` should be update within ~1 hour with this feature.

**Comment by Neirda24** [comment]
Thank you. What about resources not found ? Like css files and such ? Do we have some kind of feedback ?

**Comment by gulien** [comment]
Not currently 🤔 I'm not sure which event to catch for such a scenario. If it's the same as `net::ERR_CONNECTION_REFUSED`, there are not that much details for the end user (like the actual resource). 

On a side not, it feels like a rabbit hole of possibilities regarding the list of errors: https://source.chromium.org/chromium/chromium/src/+/main:net/base/net_error_list.h

I prefer to stick to common "errors" in order to avoid implementing everything.
